final_project/common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'common'

urlpatterns = [
    path('', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
]

final_project/sns/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'sns'

urlpatterns = [
    path('', views.sns_main, name='sns'),
    path('calorie_page', views.calorie_main, name='calorie')
]

final_project/common/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver


# Create your models here.
class User_info(models.Model):
    username = models.ForeignKey(User, null=True, on_delete=models.CASCADE, related_name="user", db_column="username", to_field="username")
    username2 = models.CharField("임시", null=True, max_length=150)
    gender = models.CharField("성별", max_length=1, null=True)
    height = models.IntegerField("키", null=True)
    weight = models.IntegerField("몸무게", null=True)
    age = models.IntegerField("나이", null=True)

final_project/common/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import User_info


class UserForm(UserCreationForm):
    email = forms.EmailField(label="이메일")

    class Meta:
        model = User
        fields = ("username", "password1", "password2", "email")

class User_infoForm(forms.ModelForm):
    class Meta:
        model = User_info
        fields = ("username2", "gender", "height", "weight", "age")

final_project/common/views.py
from django.contrib.auth import authenticate, login
from django.shortcuts import render, redirect, get_object_or_404
from .forms import UserForm, User_infoForm
from django.contrib.auth.models import User
from .models import User_info


def signup(request):
    """
    계정생성
    """
    if request.method == "POST":
        form = UserForm(request.POST)
        info = User_infoForm(request.POST)
        print(info.is_valid())
        if form.is_valid() and info.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)  # 사용자 인증
            login(request, user)  # 로그인

            # info.username = username
            info.username2 = request.POST["username"]
            info.height = request.POST["height"]
            info.gender = request.POST["gender"]
            info.weight = request.POST["weight"]
            info.age = request.POST["age"]
            info.save()

            user_obj = get_object_or_404(User, username=username)
            info_obj = get_object_or_404(User_info, username2="default")
            info_obj.username2 = request.POST["username"]
            info_obj.username = user_obj
            info_obj.save()

            return redirect('/main/')
    else:
        form = UserForm()
        info = User_infoForm()
    return render(request, 'common/signup.html', {'form': form, 'info' : info})

final_project/templates/common/form_errors.html
{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}  <!-- 필드 오류를 출력한다. -->
            <div class="alert alert-danger">
                <strong>{{ field.label }}</strong>
                {{ error }}
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}   <!-- 넌필드 오류를 출력한다. -->
        <div class="alert alert-danger">
            <strong>{{ error }}</strong>
        </div>
    {% endfor %}
{% endif %}

final_project/templates/common/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<title>Login V7</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
<!--===============================================================================================-->	
	<link rel="icon" type="image/png" href="{% static 'common/images/icons/favicon.ico' %}"/>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'common/vendor/bootstrap/css/bootstrap.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'common/fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'common/fonts/Linearicons-Free-v1.0.0/icon-font.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'common/vendor/animate/animate.css' %}">
<!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href="{% static 'common/vendor/css-hamburgers/hamburgers.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'common/vendor/animsition/css/animsition.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'common/vendor/select2/select2.min.css' %}">
<!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href="{% static 'common/vendor/daterangepicker/daterangepicker.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'common/css/util.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'common/css/main.css' %}">
<!--===============================================================================================-->
</head>
<body>
	
	<div class="limiter">
		<div class="container-login100">
			<div class="wrap-login100 p-t-90 p-b-30">
				<form method="post" class="login100-form validate-form" action="{% url 'common:login' %}">
					{% csrf_token %}
					<span class="login100-form-title p-b-40">
						Login
					</span>

					<div>
						<a href="#" class="btn-login-with bg1 m-b-10">
							<i class="fa fa-facebook-official"></i>
							Login with Facebook
						</a>

						<a href="#" class="btn-login-with bg2">
							<i class="fa fa-twitter"></i>
							Login with Twitter
						</a>
					</div>

					<div class="text-center p-t-55 p-b-30">
						<span class="txt1">
							Login
						</span>
					</div>

					<div class="wrap-input100 validate-input m-b-16" data-validate="Please enter ID">
						<input class="input100" type="text" name="username" placeholder="ID"
								id="username" value="{{ form.username.value|default_if_none:'' }}">
						<span class="focus-input100"></span>
					</div>

					<div class="wrap-input100 validate-input m-b-20" data-validate = "Please enter password">
						<span class="btn-show-pass">
							<i class="fa fa fa-eye"></i>
						</span>
						<input class="input100" type="password" name="password" placeholder="Password"
								id="password" value="{{ form.password.value|default_if_none:'' }}">
						<span class="focus-input100"></span>
					</div>

					<div class="container-login100-form-btn">
						<button class="login100-form-btn">
							Login
						</button>
					</div>
					<div class="text-center p-t-55 p-b-30">
						{% include "common/form_errors.html" %}
					</div>
					
					<div class="flex-col-c">
						<span class="txt2 p-b-10">
							Don’t have an account?
						</span>

						<a href="{% url 'common:signup' %}" class="txt3 bo1 hov1">
							Sign up now
						</a>
					</div>
					
				</form>
			</div>
		</div>
	</div>
	
	
<!--===============================================================================================-->
	<script src="{% static 'common/vendor/jquery/jquery-3.2.1.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'common/vendor/animsition/js/animsition.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'common/vendor/bootstrap/js/popper.js' %}"></script>
	<script src="{% static 'common/vendor/bootstrap/js/bootstrap.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'common/vendor/select2/select2.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'common/vendor/daterangepicker/moment.min.js' %}"></script>
	<script src="{% static 'common/vendor/daterangepicker/daterangepicker.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'common/vendor/countdowntime/countdowntime.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'common/js/main.js' %}"></script>

</body>
</html>

final_project/templates/common/signup.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<title>Login V7</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
<!--===============================================================================================-->
	<link rel="icon" type="image/png" href="{% static 'common/images/icons/favicon.ico' %}"/>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'common/vendor/bootstrap/css/bootstrap.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'common/fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'common/fonts/Linearicons-Free-v1.0.0/icon-font.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'common/vendor/animate/animate.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'common/vendor/css-hamburgers/hamburgers.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'common/vendor/animsition/css/animsition.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'common/vendor/select2/select2.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'common/vendor/daterangepicker/daterangepicker.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'common/css/util.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'common/css/main.css' %}">
<!--===============================================================================================-->
</head>
<body>
<div class="limiter">
<div class="container-login100">
    <div class="wrap-login100 p-t-90 p-b-30">
    <form method="post" class="login100-form" action="{% url 'common:signup' %}">
        {% csrf_token %}
        <div class="form-group">
            <div class="p-b">
                <span class="txt1">
                    ID
                </span>
            </div>
            <input type="text" class="form-control" name="username" id="username"
                   value="{{ form.username.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <div class="p-b">
                <span class="txt1">
                    PASSWORD
                </span>
            </div>
            <input type="password" class="form-control" name="password1" id="password1"
                   value="{{ form.password1.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <div class="p-b">
                <span class="txt1">
                    CHECK PASSWORD
                </span>
            </div>
            <input type="password" class="form-control" name="password2" id="password2"
                   value="{{ form.password2.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <div class="p-b">
                <span class="txt1">
                    E-MAIL
                </span>
            </div>
            <input type="text" class="form-control" name="email" id="email"
                   value="{{ form.email.value|default_if_none:'' }}">
        </div>
        <!-- 추가 -->
        <div class="form-group">
            <div class="p-b">
                <span class="txt1">
                    AGE
                </span>
            </div>
            <input type="text" class="form-control" name="age" id="age"
                   value="{{ info.age.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <div class="p-b">
                <span class="txt1">
                    GENDER
                </span>
            </div>
            <input type="text" class="form-control" name="gender" id="gender"
                   value="{{ info.gender.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <div class="p-b">
                <span class="txt1">
                    HEIGHT
                </span>
            </div>
            <input type="text" class="form-control" name="height" id="height"
                   value="{{ info.height.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <div class="p-b">
                <span class="txt1">
                    WEIGHT
                </span>
            </div>
            <input type="text" class="form-control" name="weight" id="weight"
                   value="{{ info.weight.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <input type="hidden" class="form-control" name="username2" id="username2"
                   value="{{ info.username2.value|default_if_none:'default' }}">
        </div>
        <!-- 추가 -->
        <div class="container-login100-form-btn">
            <button class="login100-form-btn">
                생성하기
            </button>
        </div>
        <div class="text-center p-t-55 p-b-30">
            {% include "common/form_errors.html" %}
        </div>
    </form>
</div>
</div>
</div>

<!--===============================================================================================-->
	<script src="{% static 'common/vendor/jquery/jquery-3.2.1.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'common/vendor/animsition/js/animsition.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'common/vendor/bootstrap/js/popper.js' %}"></script>
	<script src="{% static 'common/vendor/bootstrap/js/bootstrap.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'common/vendor/select2/select2.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'common/vendor/daterangepicker/moment.min.js' %}"></script>
	<script src="{% static 'common/vendor/daterangepicker/daterangepicker.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'common/vendor/countdowntime/countdowntime.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'common/js/main.js' %}"></script>

</body>
</html>