final_project/camera/urls.py
from django.urls import path
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views

app_name = 'camera_main'

urlpatterns = [
    path('', views.camera, name='camera'),
    path('get_img/', views.get_img, name='get_img'),
    path('put_meal_info/', views.put_meal_info, name='put_meal_info'),
    # url(r'^stream2/$', views.stream2, name='stream2'),
]

final_project/sns/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'sns'

urlpatterns = [
    path('', views.sns_main, name='sns'),
    path('calorie_page', views.calorie_main, name='calorie')
]

final_project/camera/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Image(models.Model):
    image_name = models.CharField(max_length=200)
    # pub_date = models.DateTimeField('date published')
    pub_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.image_name


class FoodInfo(models.Model):
    food_id = models.AutoField(primary_key=True)
    food_name = models.CharField(unique=True, max_length=200)
    calorie = models.IntegerField(default=0)

    # def __str__(self):
    #     return self.food_id


class MealInfo(models.Model):
    username = models.ForeignKey(User, null=True, on_delete=models.CASCADE, related_name="mealinfo", db_column="username", to_field="username")
    food_name = models.ForeignKey(FoodInfo, on_delete=models.CASCADE, related_name="mealinfo", db_column="food_name", to_field="food_name")
    # input_object_id = models.CharField(max_length=200)
    output_object_id = models.CharField(max_length=200)
    pub_time = models.CharField(max_length=10)
    pub_date = models.DateField(null=False)

    # def __str__(self):
    #     return self.food_name

final_project/camera/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.http import HttpResponse
from django.shortcuts import render, redirect
from rest_framework.decorators import api_view
import requests
import cv2
from .models import MealInfo, FoodInfo
import json
import numpy as np
from django.contrib.auth.models import User
from datetime import datetime


def camera(request):
    if request.method == "POST":
        print(request.POST)
        context = {'input_date': request.POST['input_date'],
                   'meal': request.POST['meal']}
        return render(request, 'camera/camera.html', context)
    else:
        return render(request, 'camera/camera.html')


@api_view(['GET', 'POST'])
def get_img(request):
    # request 받은 값 정리
    username = request.data['username']
    mealtime = request.data['meal']
    inputdate = request.data['input_date'].replace("/", "")
    context = dict(request.data)

    # 경로설정
    BASE_PATH = "C:\\PythonWork\\final_project\\final_project\\static\\userResult\\"
    origin_path = f"{BASE_PATH}{username}_{inputdate}_{mealtime}_origin.jpg"
    result_path = f"{BASE_PATH}{username}_{inputdate}_{mealtime}_result.jpg"

    # api서버 주소
    DETECTION_URL = "http://3.34.244.242:5000/rest"

    # 이미지 저장
    with open(origin_path, "wb") as f:
        for chunk in request.data['image_uploads'].chunks():
            f.write(chunk)

    # 모델에 값 전달-return
    image_data = open(origin_path, "rb").read()
    response = requests.post(DETECTION_URL, files={"image": image_data}).json()
    result = response["result"]
    result_dict = json.loads(result)[0]  # 라벨값
    labels = np.asarray(response["labels"])
    cord = np.asarray(response["cord"])
    frame = cv2.imread(origin_path)

    # 원본이미지에 결과박스 그리기, 저장
    n = len(labels)
    x_shape, y_shape = frame.shape[1], frame.shape[0]
    for i in range(n):
        row = cord[i]
        if row[4] >= 0.2:
            x1, y1, x2, y2 = int(row[0] * x_shape), int(row[1] * y_shape), int(row[2] * x_shape), int(
                row[3] * y_shape)
            bgr = (0, 255, 0)
            cv2.rectangle(frame, (x1, y1), (x2, y2), bgr, 1)
            cv2.putText(frame, result_dict["name"], (x1, y1), cv2.FONT_HERSHEY_SIMPLEX, 1, bgr, 2)
    cv2.imwrite(result_path, frame)

    # context 전달
    context['imgsrc'] = f'/static/userResult/{username}_{inputdate}_{mealtime}_result.jpg'
    del context['csrfmiddlewaretoken']
    del context['username']
    del context['image_uploads']
    context['input_date'] = context['input_date'][0]
    context['meal'] = context['meal'][0]
    context['foodname'] = result_dict["name"]

    return render(request, 'camera/get_img.html', context)


@api_view(['GET', 'POST'])
def put_meal_info(request):
    my_food = request.data['foodname']
    if my_food == 'Sushi':
        my_food = '초밥'
    elif my_food == 'Udon':
        my_food = '우동'
    elif my_food == 'Champon':
        my_food = '짬뽕'
    elif my_food == 'Jajangmyeon':
        my_food = '짜장면'
    elif my_food == 'Fried Chicken':
        my_food = '치킨'
    elif my_food == 'Pizza':
        my_food = '피자'

    username = User.objects.get(username=request.data['username'])
    food_name = FoodInfo.objects.get(food_name=my_food)

    dateString = request.data['input_date'].replace('/', '-')
    dateFormatter = '%m-%d-%Y'
    input_date = datetime.strptime(dateString, dateFormatter).date()

    result = MealInfo.objects.filter(username=username, pub_date=input_date, pub_time=request.data['meal']).values_list('pk', flat=True)

    if result:
        item = MealInfo.objects.get(pk=result[0])
        item.delete()

    MealInfo.objects.create(username=username,
                            food_name=food_name,
                            output_object_id=request.data['imgsrc'],
                            pub_time=request.data['meal'],
                            pub_date=input_date)

    return redirect('/main/')

final_project/templates/camera/camera.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<!-- calorie info -->
<div class="container" style="margin-bottom: 50px;">
    <div class="row">
        <div class="col-md-12">
            <div class="main_heading">
                <h1>Camera</h1>
                <div class="text-center"><span class="underline"></span></div>
            </div>
        </div><!-- End col-md-12 -->
    </div><!-- End row -->
<!--    <input type="file" accept="image/*" id="file-input">-->
    <div id="tabs">
    <ul>
        <li id="calorie_specific_date"><a href="#tabs_camera">사진 촬영/선택</a></li>
    </ul>
    <div id="image_iuput_form" style="margin-top: 25px; margin-bottom: 20px;">
        {% if input_date %}
    <form method="post" action="{% url 'camera_main:get_img' %}" enctype="multipart/form-data">
        {% csrf_token %}
        <input type="text" aria-label="input_date" value="{{input_date}}" id="input_date" name="input_date" class="datepicker text-center" readonly="readonly" style="margin-right: 10px;">
        {% if meal == 'breakfast' %}
        <input type="radio" id="breakfast" name="meal" value="breakfast" checked>
        {% else %}
        <input type="radio" id="breakfast" name="meal" value="breakfast">
        {% endif %}
        아침
        {% if meal == 'lunch' %}
        <input type="radio" id="lunch" name="meal" value="lunch" checked>
        {% else %}
        <input type="radio" id="lunch" name="meal" value="lunch">
        {% endif %}
        점심
        {% if meal == 'dinner' %}
        <input type="radio" id="dinner" name="meal" value="dinner" checked>
        {% else %}
        <input type="radio" id="dinner" name="meal" value="dinner">
        {% endif %}
        저녁
        <div class="preview" id="preview" style="margin-top: 20px;">
            <p>No files currently selected for upload</p>
        </div>
        <div style="text-align : right;">
            <label for="image_uploads">Choose images to upload (PNG, JPG)</label>
            <button>Submit</button>
            <input type="file" id="image_uploads" name="image_uploads" accept="image/*" multiple>
            {% if user.is_authenticated %}
            <input type="hidden" name="username" value="{{ user.username }}">
            {% endif %}
        </div>
    </form>
        {% else %}
        <form method="post" action="{% url 'camera_main:get_img' %}" enctype="multipart/form-data">
        {% csrf_token %}
        <input type="text" aria-label="input_date" v-model="input_date" id="input_date" name="input_date" class="datepicker text-center" readonly="readonly">
        <input type="radio" id="breakfast" name="meal" value="breakfast">
        아침
        <input type="radio" id="lunch" name="meal" value="lunch" checked>
        점심
        <input type="radio" id="dinner" name="meal" value="dinner">
        저녁
        <div class="preview" id="preview">
            <p>No files currently selected for upload</p>
        </div>
        <div style="text-align : right;">
            <label for="image_uploads">Choose images to upload (PNG, JPG)</label>
            <button>Submit</button>
            <input type="file" id="image_uploads" name="image_uploads" accept="image/*" multiple>
            {% if user.is_authenticated %}
            <input type="hidden" name="username" value="{{ user.username }}">
            {% endif %}
        </div>
    </form>
        {% endif %}
    </div>
    </div>
</div><!-- End container -->
{% endblock %}

final_project/templates/camera/get_img.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<!-- calorie info -->
<div class="container" style="margin-bottom: 50px;">
    <div class="row">
        <div class="col-md-12">
            <div class="main_heading">
                <h1>Camera</h1>
                <div class="text-center"><span class="underline"></span></div>
            </div>
        </div><!-- End col-md-12 -->
    </div><!-- End row -->
<!--    <input type="file" accept="image/*" id="file-input">-->
    <div id="tabs">
    <ul>
        <li id="calorie_specific_date"><a href="#tabs_camera">사진 확인</a></li>
    </ul>
    <div id="image_iuput_form" style="margin-top: 20px; margin-bottom: 20px;">
    <form method="post" action="{% url 'camera_main:put_meal_info' %}" enctype="multipart/form-data">
        {% csrf_token %}
        <input type="text" aria-label="input_date" value="{{input_date}}" class="datepicker text-center" disabled>
        <input type="hidden" aria-label="input_date" value="{{input_date}}" id="input_date" name="input_date" class="datepicker text-center" readonly="readonly">
        {% if meal == 'breakfast' %}
        <input type="radio" id="breakfast" name="meal" value="breakfast" checked>
        {% else %}
        <input type="radio" id="breakfast" name="meal" value="breakfast" disabled>
        {% endif %}
        아침
        {% if meal == 'lunch' %}
        <input type="radio" id="lunch" name="meal" value="lunch" checked>
        {% else %}
        <input type="radio" id="lunch" name="meal" value="lunch" disabled>
        {% endif %}
        점심
        {% if meal == 'dinner' %}
        <input type="radio" id="dinner" name="meal" value="dinner" checked>
        {% else %}
        <input type="radio" id="dinner" name="meal" value="dinner" disabled>
        {% endif %}
        저녁
        <div class="userResult" id="userResult">
            <ol>
                <li>
                    <img src="{{imgsrc}}">
                </li>
            </ol>
        </div>
        <div style="text-align : right;">
            <button type="submit" formaction="{% url 'camera_main:camera' %}" formmethod="post">사진교체</button>
            <button>저장하기</button>
            {% if user.is_authenticated %}
            <input type="hidden" name="username" value="{{ user.username }}">
            <input type="hidden" name="foodname" value="{{ foodname }}">
            <input type="hidden" name="imgsrc" value="{{ imgsrc }}">
            {% endif %}
        </div>
    </form>
    </div>
    </div>
</div><!-- End container -->
{% endblock %}